apiVersion: v1
kind: Namespace
metadata:
  name: kind-test
  labels:
    istio-injection: enabled

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellowd
  namespace: kind-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellowd
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hellowd
    spec:
      containers:
        - name: hellowd
          image: hellowd
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250Mi
